# Generated by Django 5.1 on 2024-09-11 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Data_cadastro', models.DateField(null=True)),
                ('Data_Nascimento', models.DateField(null=True)),
                ('Estado_civil', models.CharField(max_length=100, null=True)),
                ('Grupo', models.CharField(max_length=100, null=True)),
                ('Situacao_atual', models.CharField(max_length=100, null=True)),
                ('observacoes', models.CharField(max_length=256, null=True)),
                ('genero', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=20, null=True)),
                ('clinica', models.CharField(max_length=100, null=True)),
                ('local_nascimento', models.CharField(max_length=100, null=True)),
                ('CPF', models.CharField(max_length=100, null=True)),
                ('RG', models.CharField(max_length=100, null=True)),
                ('Orgao_emissor', models.CharField(max_length=100, null=True)),
                ('Convenio', models.CharField(max_length=100, null=True)),
                ('Plano', models.CharField(max_length=100, null=True)),
                ('Data_adesao', models.DateField(null=True)),
                ('Nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('CPF_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('RG_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefone_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('Nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('Cpf_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('Rg_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefone_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('CEP', models.IntegerField(null=True)),
                ('Endereco', models.CharField(max_length=100, null=True)),
                ('Numero', models.IntegerField(null=True)),
                ('Complemento', models.CharField(max_length=100, null=True)),
                ('Bairro', models.CharField(max_length=100, null=True)),
                ('Cidade', models.CharField(max_length=100, null=True)),
                ('Estado', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente1', models.TextField(blank=True, null=True)),
                ('dente2', models.TextField(blank=True, null=True)),
                ('dente3', models.TextField(blank=True, null=True)),
                ('dente4', models.TextField(blank=True, null=True)),
                ('dente5', models.TextField(blank=True, null=True)),
                ('dente6', models.TextField(blank=True, null=True)),
                ('dente7', models.TextField(blank=True, null=True)),
                ('dente8', models.TextField(blank=True, null=True)),
                ('dente9', models.TextField(blank=True, null=True)),
                ('dente10', models.TextField(blank=True, null=True)),
                ('dente11', models.TextField(blank=True, null=True)),
                ('dente12', models.TextField(blank=True, null=True)),
                ('dente13', models.TextField(blank=True, null=True)),
                ('dente14', models.TextField(blank=True, null=True)),
                ('dente15', models.TextField(blank=True, null=True)),
                ('dente16', models.TextField(blank=True, null=True)),
                ('dente17', models.TextField(blank=True, null=True)),
                ('dente18', models.TextField(blank=True, null=True)),
                ('dente19', models.TextField(blank=True, null=True)),
                ('dente20', models.TextField(blank=True, null=True)),
                ('dente21', models.TextField(blank=True, null=True)),
                ('dente22', models.TextField(blank=True, null=True)),
                ('dente23', models.TextField(blank=True, null=True)),
                ('dente24', models.TextField(blank=True, null=True)),
                ('dente25', models.TextField(blank=True, null=True)),
                ('dente26', models.TextField(blank=True, null=True)),
                ('dente27', models.TextField(blank=True, null=True)),
                ('dente28', models.TextField(blank=True, null=True)),
                ('dente29', models.TextField(blank=True, null=True)),
                ('dente30', models.TextField(blank=True, null=True)),
                ('dente31', models.TextField(blank=True, null=True)),
                ('dente32', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bloco', models.IntegerField()),
                ('color', models.CharField(default='#cccccc', max_length=7)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('confirmacao', models.CharField(blank=True, max_length=100, null=True)),
                ('dentista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cadeira', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cadeira')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
