# Generated by Django 5.1 on 2024-09-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_odontograma_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontograma',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
