# Generated by Django 5.1 on 2024-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_financeiro_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
