# Generated by Django 5.1 on 2024-10-22 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_financeiro_numero_parcela_alter_financeiro_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='data_de_cobranca',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='numero_parcela',
            field=models.PositiveIntegerField(),
        ),
    ]
