# Generated by Django 5.1 on 2024-10-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_financeiro_data_de_cobranca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='data_de_pagamento',
        ),
    ]
