# Generated by Django 5.1 on 2024-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_financeiro_codigo_receita_financeiro_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
