# Generated by Django 5.1 on 2024-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_financeiro_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
