# Generated by Django 5.1 on 2024-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_financeiro_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='periodo_apuracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
