# Generated by Django 5.1 on 2024-10-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_financeiro_periodo_apuracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='periodo_apuracao',
        ),
    ]
